If receive api
Game-as-a-Service/The-Message pull request #109
Opened 2024-01-25 07:43 UTC by qscez2001

https://github.com/Game-as-a-Service/The-Message/issues/92

2024-01-27 22:24 UTC, linycken013127 requested changes
Review Donw.

2024-01-27 22:24 UTC, linycken013127 commented on Backend/service/delivery/http/v1/player_handler.go
> +		c.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
這邊改動的原因是？

2024-01-28 01:40 UTC, qscez2001 commented on Backend/service/delivery/http/v1/player_handler.go
> +		c.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
應該是解conflict時候改到了... 已修正

2024-01-28 01:48 UTC, linycken013127 approved these changes
LGMT

2024-01-28 01:48 UTC, merged